export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAILED = "CURRENT_USER_FAILED";
export const EMP_CREATE_SUCCESS = "EMP_CREATE_SUCCESS";
export const EMP_ALL_SUCCESS = "EMP_ALL_SUCCESS";
export const EMP_SINGLE_SUCCESS = "EMP_SINGLE_SUCCESS";
export const EMP_FAILED = "EMP_FAILED";
export const SALARY_HISTORY_SUCCESS = "SALARY_HISTORY_SUCCESS";
export const SALARY_HISTORY_FAILED = "SALARY_HISTORY_FAILED";